### ISSUE TITLE
demo程序处理文本消息时反馈invalid request

### ISSUE THREAD

**Issue by samsong8610** [jeffkit/wechat#19]
从源码看，是`is_valid_params()`返回None了。在views中加日志确定，作为`app.process(request.GET, request.body)`中的`request.GET`是空集合。

根据[微信开发者文档-接收普通消息](http://mp.weixin.qq.com/wiki/17/f298879f8fb29ab98b2f2971d42552fd.html#.E6.96.87.E6.9C.AC.E6.B6.88.E6.81.AF) ，微信post到url的请求没有参数，所以这种情况是不是就不应该检查params了。

是不是可以通过检查请求方法是GET还是POST来判断要不要验证参数？

**Comment by jeffkit** [comment]
Post到URL的请求同样要求有签名参数的。如果Post请求不要求签名参数，安全性无法保障。在Post XML消息的同时，QueryString还是要加签名参数，这种情况下，GET和POST都是会有数据的，也就是说GET参数一直都不能是空集合。
