### ISSUE TITLE
企业号回调模式回复中文消息微信中没有反应

### ISSUE THREAD

**Issue by sumw3** [jeffkit/wechat#6]
如题，在```WxTextResponse(result, req)```中如果result是包含中文的话，微信客户端没有反应；如果只是英文和数字没有问题，考虑应该是编码的问题导致微信端解密失败，目前还没发现哪个地方有问题。

**Comment by jeffkit** [comment]
你好，这个问题在最新的版本中已经修复，谢谢反馈
